"""Add_Types_and_Drugs_tables

Revision ID: 3754fdf4c66c
Revises: 257048bdef75
Create Date: 2020-05-01 15:38:46.944939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3754fdf4c66c'
down_revision = '257048bdef75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('legal_status', sa.Text(), nullable=True),
    sa.Column('drug_testing', sa.Text(), nullable=True),
    sa.Column('way_consuming', sa.Text(), nullable=True),
    sa.Column('desired_effect', sa.Text(), nullable=True),
    sa.Column('secondary_effect', sa.Text(), nullable=True),
    sa.Column('risks_complications', sa.Text(), nullable=True),
    sa.Column('addiction', sa.Text(), nullable=True),
    sa.Column('risk_reduction_tips', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['Types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Drugs')
    op.drop_table('Types')
    # ### end Alembic commands ###
