"""add_takes_table

Revision ID: 6482307be9ec
Revises: 3754fdf4c66c
Create Date: 2020-05-02 15:04:00.719376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6482307be9ec'
down_revision = '3754fdf4c66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('adress', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.String(length=150), nullable=True),
    sa.Column('longitude', sa.String(length=150), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['Drugs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Takes')
    # ### end Alembic commands ###
