"""empty message

Revision ID: b63656b5f4e2
Revises: 6482307be9ec
Create Date: 2020-05-05 20:07:08.948673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63656b5f4e2'
down_revision = '6482307be9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Drugs', sa.Column('img', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Drugs', 'img')
    # ### end Alembic commands ###
